[package]
name = "deschiffres"
version = "0.5.0"
edition = "2021"

[lib]
# crate-type = ["cdylib"]

[features]
wasm = []

[dependencies]
crossbeam-channel = { version = "0.5.6", features = ["crossbeam-utils"] }
crossbeam-utils = "0.8.14"
itertools = "0.10.5"